language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
cache: yarn
before_install:
# Use newer yarn than that pre-installed in the Travis image.
- curl -sSfL https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
